name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKFLOW_F0704 }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_TASKFLOW_F0704" > ${HOME}/firebase-service-account.json
          firebase login:ci --no-localhost
          firebase use taskflow-f0704
          firebase deploy --only hosting --project taskflow-f0704 --token "$(firebase login:ci --no-localhost)"

